name: attendify
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.1


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.1.0 #documentation link: https://pub.dev/packages/flutter_dotenv
  google_fonts: ^6.2.1 #documentation link: https://pub.dev/packages/google_fonts
  mobile_scanner: ^5.2.3 #documentation link https://pub.dev/packages/mobile_scanner
  pretty_qr_code: ^3.3.0 #documentation link https://pub.dev/packages/pretty_qr_code
  http: ^1.2.2
  shared_preferences: ^2.3.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - .env

